apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: go-fibo-deployment
spec:
  selector:
    matchLabels:
      app: go-fibo
  replicas: 4 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: go-fibo
    spec:
      containers:
      - name: go-fibo
        image: damianjaniszewski/go-fibo:0.02
        env:
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
        readinessProbe:
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 8
          # Amount of time to wait before timing out
          timeoutSeconds: 1
          # Probe for http
          httpGet:
            # Path to probe
            path: /svc/health
            # Port to probe
            port: 80
        livenessProbe:
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 4
          # Amount of time to wait before timing out
          timeoutSeconds: 1
          # Probe for http
          httpGet:
            # Path to probe
            path: /svc/health
            # Port to probe
            port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: go-fibo
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: go-fibo
